name: Android Build and Firebase Upload

on:
  pull_request:       # ✅ Triggers on ALL pull requests
    branches:
      - '**'          # Targets any branch
  push:
    branches:
      - main          # Optional: Also run on push to main

jobs:
  build:
    name: Build and Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: internal-testers  # change to your Firebase tester group
          file: app/build/outputs/apk/release/app-release.apk
