name: Android Build and Firebase Upload

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Generate Release Notes with Run Number
        run: |
          echo "Version: Build #${{ github.run_number }}" > release-notes.txt
          echo "PR: ${{ github.event.pull_request.html_url || github.ref }}" >> release-notes.txt
          echo "Commit: ${{ github.sha }}" >> release-notes.txt

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: internal-testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotesFile: release-notes.txt