name: Android Build and Firebase Upload

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Extract buildNumber from PR or Branch
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "buildNumber=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          else
            echo "buildNumber=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Build APK with buildNumber
        run: ./gradlew assembleDebug -PbuildNumber=${{ steps.vars.outputs.buildNumber }}

      - name: Generate Release Notes with Branch Name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Build from branch: $BRANCH_NAME" > release-notes.txt
          echo "Commit: $GITHUB_SHA" >> release-notes.txt
          echo "Triggered by: $GITHUB_ACTOR" >> release-notes.txt
          echo "Build Number: ${{ steps.vars.outputs.buildNumber }}" >> release-notes.txt

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: internal-testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotesFile: release-notes.txt
